CREATE TABLE TblEntity (
	Id INT IDENTITY,
	Titulo VARCHAR(50),
	Editorial VARCHAR(30),
	Genero VARCHAR(30)
)
--ALTER TABLE TblEntity ADD CONSTRAINT PK_Id PRIMARY KEY (Id)

SELECT
	*
FROM TblEntity WITH(NOLOCK)

--TRUNCATE TABLE TblEntity